drop table refresh_sessions;
drop table "order";
drop table comment;
drop table coach_service;
drop table abonement_service;
drop table coach;
drop table "user";
drop table service;
drop table abonement;